name: tetris
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_neumorphic: ^3.0.4+1
  material_design_icons_flutter: ^4.0.5855
  neumorphic: ^0.4.0
  overlay_support: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/material.png
